title: My Blog
author: Alexandra E Hill
email: alihill@ucdavis.edu
description: > # this means to ignore newlines until "baseurl:"
  Some sort of description.

# social links
twitter_username: your-twitter-handle
github_username:  AlexandraEHill

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
